iscsistart: Fix iscsistart timeout during login session
open-iscsi/open-iscsi pull request #275
Opened 2021-09-13 16:27 UTC by jkhasdev-ora

When iscsistart places a login request during boot, if it gets timeout
and response receive after it. It triggers "connection1:0: detected conn
error (1011)", since in userspace nobody is listening.

On OL6, it has been observed where iscsid is not part of initramfs.

During boot, iscsistart forks and child process used as placing a request whereas
parent wait in event loop.

In the child, login_seesion places login request, and request gets
timed-out then parent also exit. If it receive response for timed-out
request and during that time no parent is listening to it then it will
error as 1011.

This patch adds an additional option to increase tmo for login request
timeout. This patch has been tested some intesive workload by increase it as 6x
and helps resolve the issue.

Signed-off-by: Jitendra Khasdev <jitendra.khasdev@oracle.com>

2021-09-18 23:18 UTC, gonzoleeman commented
I closed the other ("[OLD]") pull request, and now this one seem  broken. When I try to look at the diffs, it says HTML 404 error page not found?

2021-09-21 17:57 UTC, gonzoleeman requested changes
The issistart man page also needs to be updated. Please add that.

2021-09-21 17:57 UTC, gonzoleeman commented on usr/iscsistart.c
> +		int tmo = ISCSID_REQ_TIMEOUT * login_req_timeout;
I don't like multiplying ISCSID_REQ_TIMEOUT times the login_req_timeout. It just so happens that currently ISCSID_REQ_TIMEOUT is one second, but what if it changes to 5 seconds? Then your iscsistart timout would multiply times 5! Can you just login_req_timeout not depend on ISCSID_REQ_TIMEOUT?

2021-12-03 18:21 UTC, gonzoleeman commented
One last small change requested. Can you please update your branch so I can pull your request?

2021-12-03 19:37 UTC, mikechristie commented
Hey Lee, jkhasdev-ora is no longer at oracle and is free from iscsi :)

Me on the other hand.... is hopefully temporarily helping out :)

This patch is wrong. I'm going to close this and will open a new PR.

2021-12-03 19:37 UTC, closed without merging