Add ability to specify name-value parameters when creating a new iface
open-iscsi/open-iscsi pull request #342
Opened 2022-04-14 13:38 UTC by wenchao-hao

Add ability to specify name-value parameters when creating a new iface
like following:

root# iscsiadm -m iface -I test -o new -n iface.initiatorname -v iqn.2016-04.com.open-iscsi:17a3c9bc2d
test updated.
New interface test added
root# iscsiadm -m iface -I test | grep initiatorname
iface.initiatorname = iqn.2016-04.com.open-iscsi:17a3c9bc2d

Signed-off-by: Wenchao Hao <haowenchao@huawei.com>

2022-05-07 20:43 UTC, gonzoleeman requested changes
This looks fine, but I believe you also need to update the usage message and the man page. If you'd like help on wording for the man page, let me know.

2022-05-09 01:50 UTC, wenchao-hao commented
> This looks fine, but I believe you also need to update the usage message and the man page. If you'd like help on wording for the man page, let me know.
I don't know how to update the man page...

2022-05-16 16:15 UTC, gonzoleeman commented
Ping @wenchao-hao  ???

2022-05-17 17:43 UTC, wenchao-hao commented
> Ping @wenchao-hao  ???

I don't know how to change the man page, could you help？

2022-05-20 17:02 UTC, gonzoleeman commented
> 

Sure. I'll cobble together something. It's really not hard. If you look at the man page, it's just "nroff/troff".

2022-05-20 17:15 UTC, gonzoleeman commented
> > 
> 
> Sure. I'll cobble together something. It's really not hard. If you look at the man page, it's just "nroff/troff".

LOL. I'm an idiot.

I didn't check the existing code nor the man page before I asked you to update them.

Turns out the "usage()" in iscsiadm and the man page **both** say that "iscsiadm -m iface ..." accepts name/value pairs already! So it was really a bug that the code wasn't really doing that.

2022-05-20 17:16 UTC, merged

2022-05-20 17:16 UTC, gonzoleeman commented
thank you for your submission and for your patience.