Correctly set the oom_score_adj score value to the equivalent of oom_adj
open-iscsi/open-iscsi pull request #376
Opened 2022-10-04 09:43 UTC by kalampakas

It looks like when the change to new path was made the value used was the expected for oom_adj but oom_score_adj uses values between -1000 and 1000, so it looks like with the same intention in mind ( avoid killing iscsid when oom_killer is invoked ), the value should be -1000. 
This is according to https://www.kernel.org/doc/Documentation/filesystems/proc.rst , section 3.1, OOM_SCORE_ADJ_MIN, which under a regular kernel release should be -1000 ( https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/include/uapi/linux/oom.h )
Quoting:  "The lowest possible value, -1000, is equivalent to disabling oom killing entirely for that task since it will always report a badness score of 0."

2022-10-06 17:29 UTC, gonzoleeman commented
I appreciate your submission, but after looking over this code, I think it needs more than this.

It looks like "-17" is the max value that /proc/self/oom_adj takes, and "-1000" is the max value that /proc/self/oom_socre_adj takes. Based on that, this code currently appears to try to use oom_score_adj first, then falls back to the older oom_adj. Then it tries to write "-16", assuming that will work with either (I guess), then sends "-17".

But looking at other code and searching on lwn.net and other places, it looks like the code is wrong even in it's simplistic approach.

I would like the code to do something like this:

```
if you can find /proc/self/oom_score_adj then
    write -1000 to that
else if you can find /proc/self/oom_adj then
    write -17 to that
else
    print a warning
if we wrote a value and it fails then
    print a warning

```
There's no reason to get our own pid when /proc/self works.

If you would like to update your submission to clean this up, I'd be glad to accept it. (If you don't, I will.)

2022-10-07 11:56 UTC, kalampakas commented
I've tried a refactor based on your comments whether or not you include that or rewrite it somehow else is not important but I think that getting the pid is safer than trying to use self because it was introduced in a later version.

2022-10-08 00:03 UTC, ericwmackay requested changes
Need to adjust the amount of bytes being written

2022-10-08 07:44 UTC, kalampakas commented on iscsiuio/src/unix/main.c
> +		else if (write(fd, score, 3) < 0) {
this has been rewritten with the latest commit

2022-10-08 07:44 UTC, kalampakas commented on usr/iscsi_util.c
> +		else if (write(fd, score, 3) < 0) {
this has been rewritten with the latest commit

2022-10-10 22:57 UTC, ericwmackay commented on iscsiuio/src/unix/main.c
> +		len = strlen(score);
snprintf already returns the number of characters it printed.

Your code will work, but there's no reason to call another function.

2022-10-10 22:59 UTC, ericwmackay commented on usr/iscsi_util.c
> +		len = strlen(score);
Same as above. You can just do len = snprintf(.... etc

Ideally, you should also check that the return of snprintf is non-negative, so you can catch errors

2022-10-10 23:03 UTC, ericwmackay commented on iscsiuio/src/unix/main.c
> +		else if (write(fd, score, 3) < 0) {
Looks better now

2022-10-10 23:05 UTC, ericwmackay commented on usr/iscsi_util.c
> +		else if (write(fd, score, 3) < 0) {
Looks better now

2022-10-11 23:45 UTC, gonzoleeman commented
This seems to have gotten too complicated.

Here's what I'm proposing:
```
	if ((fd = open("/proc/self/oom_score_adj", O_WRONLY)) >= 0) {
		if ((res = write(fd, "-1000", 5)) < 0)
			log_warning("Could not set /proc/self/oom_score_adj to -1000: %s",
				strerror(errno));
	} else if ((fd = open("/proc/self/oom_adj", O_WRONLY)) >= 0) {
		if ((res = write(fd, "-16", 3)) < 0)
			log_warning("Could not set /proc/self/oom_adj to -16: %s",
				strerror(errno));
	} else
		return -1;

	close(fd);
	if (res < 0)
		return res;
	else
		return 0;

```

I will submit this as a pull request, so you can comment on it. I welcome your input!

2022-10-11 23:46 UTC, gonzoleeman commented
Please see pull request #377

2022-10-12 17:06 UTC, gonzoleeman commented
Closing this as it is superseded by #377

2022-10-12 17:06 UTC, closed without merging